# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "ubuntu/trusty64"
  # config.vm.network :private_network, ip: "10.1.2.10"

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "test.yml"
    ansible.sudo = true


  end
end