- name: Copy configuration file for logrotate cdtool log.
  copy: 
    src=cdtool_logrotate.conf
    dest=/etc/logrotate.d/cdtool_logrotate.conf
    mode=644
  tags:
    - logrotate

- name: Copy configuration file for logrotate haproxy log.
  copy: 
    src=haproxy_logrotate.conf
    dest=/etc/logrotate.d/haproxy_logrotate.conf
    mode=644
  tags:
    - logrotate


- name: Copy configuration file for logrotate nginx log.
  copy: 
    src=nginx_logrotate.conf
    dest=/etc/logrotate.d/nginx_logrotate.conf
    mode=644
  tags:
    - logrotate


- name: Copy configuration file for logrotate applog log.
  copy: 
    src=applog_logrotate.conf
    dest=/etc/logrotate.d/applog_logrotate.conf
    mode=644
  tags:
    - logrotate