- name: Create rsyslog.d configuration directory
  become: yes
  file:
    path: /etc/rsyslog.d
    owner: root
    group: root
    mode: 0755
    state: directory
  tags:
    - rsyslog

- name: Copy configuration file for nginx log.
  copy: 
    src="{{ item }}"
    dest=/etc/rsyslog.d/"{{ item }}"
    mode=644
  with_items:
    - 30-nginx-log.conf
    - 31-haproxy-log.conf
    - 32-cdtool-log.conf

  notify:
    - restart rsyslog
  tags:
    - rysslog

- name: Create application specific configuration files
  become: yes
  template:
    src: app-log.conf.j2
    dest: /etc/rsyslog.d/10-app-log.conf
    owner: root
    group: root
    mode: 0644
  notify:
    - restart rsyslog
  tags:
    - rsyslog


- name: Create consul specific configuration files
  become: yes
  template:
    src: consul-log.conf.j2
    dest: /etc/rsyslog.d/12-consul-log.conf
    owner: root
    group: root
    mode: 0644
  notify:
    - restart rsyslog
  tags:
    - rsyslog
