---
# tasks file for rsyslog (Ubuntu specific)

- name: Install rsyslog packages
  become: yes
  apt:
    name: "{{ item }}"
    state: installed
    # update_cache: yes
  with_items:
    - "{{ rsyslog_packages }}"
  tags:
    - rsyslog
