---
# defaults file for rsyslog

rsyslog_repeated_msg_reduction: "on"
rsyslog_action_file_default_template: RSYSLOG_TraditionalFileFormat
rsyslog_klog_permit_non_kernel_facility: "on"
rsyslog_udp_enable: false
rsyslog_udp_address: 127.0.0.1
rsyslog_udp_port: 514
rsyslog_tcp_enable: false
rsyslog_tcp_port: 514
rsyslog_apps: 
  - hd1-cas 
  - hd1-sms-gateway
  - hd1-billing
  - hd1-cm-ubs
  - hd1-payment
  - hd1-partner
  - hd1-mediaresource
  - hd1-stream-session
  - hd1-socket
  - hd1-movies
  - hd1-mobile-movies
  - hd1-admintool
  - hd1-code-partners
  - hd1-smart-device
  - hd1-mbf-4g
  - hd1-cm
  - hd1-mbf
  - hd1-crm
  - hd1-static
envs: 
  - sand
  - stag
  - prod